# Generated by Django 3.2.23 on 2024-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
