# Generated by Django 3.2 on 2024-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
