# Generated by Django 3.2.23 on 2024-02-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sight', '0002_review_teacher_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor_sight.teacherprofile'),
        ),
    ]
