# Generated by Django 3.2.23 on 2024-02-11 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sight', '0004_auto_20240211_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='availability',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(default='Monday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='expertise',
            field=models.CharField(default='Maths', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
